export const legalContentEn = {
  terms: `<h1>Terms of Use</h1><p><em>Last updated: 27 September 2026</em></p>
<h2>1. Website information</h2><p>This website is owned and operated by:</p><p><strong>Name / trading name:</strong> Nataliia Krasovska<br/><strong>Legal status:</strong> Autónomo (self-employed individual)<br/><strong>Professional address:</strong> Talula Head &amp; SPA, C/ de la Font de la Figuera, 7, Quatre Carreres, 46004 València, Valencia, Spain<br/><strong>E-mail:</strong> <a href="mailto:krasovska1993@gmail.com">krasovska1993@gmail.com</a><br/><strong>NIF/NIE:</strong> [ADD NIF/NIE]</p><p>This website provides information about hairdressing services provided by Nataliia Krasovska and allows users to contact her or make an appointment.</p>
<h2>2. Acceptance of these Terms</h2><p>By using this website, you agree to these Terms of Use, the Privacy Policy and the Cookie Policy.</p><p>If you do not agree with these terms, please do not use the website.</p>
<h2>3. Information about services</h2><p>Information about hairdressing services, prices, duration and availability published on the website may change.</p><p>Appointments are made through the external online booking service Cal.com. During booking, users may be asked for their name, contact details and other information necessary to arrange their visit.</p>
<h2>4. Online booking</h2><p>The website may redirect you to Cal.com to book a service.</p><p>Cal.com is an independent provider of an online booking platform. Data entered during booking is processed in accordance with Cal.com's terms and privacy policy.</p><p>Cal.com's current Privacy Policy is available on its website.</p>
<h2>5. Intellectual property</h2><p>Unless otherwise stated, the text, photographs, graphics, logos, design and other materials on this website belong to Nataliia Krasovska or are used lawfully.</p><p>Copying, reproduction, distribution or commercial use of website materials without prior permission is prohibited unless permitted by law.</p>
<h2>6. External links</h2><p>This website may contain links to third-party websites or services, including Cal.com.</p><p>Nataliia Krasovska does not control the operation, content or privacy policies of third-party services and is not responsible for their activities.</p><p>Use of third-party services is governed by their own terms and policies.</p>
<h2>7. Liability</h2><p>Information on this website is provided for informational purposes and is updated as far as reasonably possible.</p><p>Nataliia Krasovska does not guarantee that the website will be continuously available or free of technical errors.</p><p>Nataliia Krasovska is not responsible for temporary website unavailability, technical failures or problems caused by third-party services.</p>
<h2>8. Applicable law and jurisdiction</h2><p>These Terms of Use are governed by the laws of Spain.</p><p>Any dispute is subject to the competent court and jurisdiction rules established by applicable Spanish law and consumer protection legislation, where applicable.</p>
<h2>9. Changes</h2><p>Nataliia Krasovska reserves the right to amend this document if there are changes in the law, services or website functionality.</p><p>The current version is always published on this page.</p>`,
};
