import { FormEvent } from 'react';
import { Copy, Language, services } from './content';
import { Info, SectionHeading } from './SectionHeading';

type ContactSectionProps = { language: Language; text: Copy; sent: boolean; onSubmit: (event: FormEvent<HTMLFormElement>) => void };

export function ContactSection({ language, text, sent, onSubmit }: ContactSectionProps) {
  return <section id="contact" className="bg-white px-5 py-24 lg:px-10"><div className="mx-auto max-w-5xl"><SectionHeading title={text.visitTitle} intro={text.visitIntro} /><div className="grid gap-12 md:grid-cols-2"><div className="space-y-7"><Info label={language === 'uk' ? 'Адреса' : 'Address'} value={text.address} /><Info label={language === 'uk' ? 'Телефон' : 'Phone'} value="+38 (099) 123-45-67" /><Info label={language === 'uk' ? 'Графік роботи' : 'Opening hours'} value={text.hours} /><Info label="Instagram" value="@lelegance_beauty" /></div><form className="space-y-4" onSubmit={onSubmit}><input required placeholder={text.name} className="w-full border border-[#e0e0e0] px-4 py-3 outline-none focus:border-[#d4a373]" /><input required type="tel" placeholder={text.phone} className="w-full border border-[#e0e0e0] px-4 py-3 outline-none focus:border-[#d4a373]" /><select required defaultValue="" className="w-full border border-[#e0e0e0] bg-white px-4 py-3 outline-none focus:border-[#d4a373]"><option value="" disabled>{text.service}</option>{services.map((item) => <option key={item.title.en}>{item.title[language]}</option>)}</select><textarea rows={4} placeholder={text.comment} className="w-full resize-none border border-[#e0e0e0] px-4 py-3 outline-none focus:border-[#d4a373]" /><button className="w-full rounded-full bg-[#d4a373] px-5 py-4 text-sm font-semibold uppercase tracking-[0.08em] text-white hover:bg-[#bc8a5f]">{text.submit}</button>{sent && <p className="bg-[#faf1e5] p-4 text-sm text-[#6c757d]">{text.sent}</p>}</form></div></div></section>;
}
